name: run-tests

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run Unit tests
        run: ./vendor/bin/phpunit --testsuite units

      - name: Run Mutation tests
        run: ./vendor/bin/infection --threads=2 --logger-github
